Update Drinking-Machine-Arduino-Code.ino
Tauheed-Elahee/Drinking-Machine-Arduino-Code pull request #1
Opened 2019-03-05 19:00 UTC by seththompsonn

Skeleton of the Arduino code with SOME flesh added to it. Once data pins are fully mapped I (Seth) will change logic values for dataflow

2019-03-05 19:20 UTC, Tauheed-Elahee approved these changes
Nice job Seth.

2019-03-07 22:17 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +    Difference between Metro and Chrono Library is that metro repeats on a set interval, and
Remove comment

2019-03-07 22:18 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +bool game = false;
remove game and Bluetooth variables, not being used

2019-03-07 22:19 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +/*
Remove comment,

Can refer to the state diagram to explain the state enum

2019-03-07 22:19 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +int inputdelay = 500;
indicate delay is in milliseconds.

2019-03-07 22:22 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +const int buttonblank1 = 0;
Should be LOW instead of 0.

2019-03-07 22:23 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +  polling = true;
Do not included commented out code in review, either delete or remove comment.

2019-03-07 22:27 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +  MANUAL_POLLING,
Unclear naming

2019-03-07 22:29 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +  MANUAL_POLLING,
Should not use generic names like Polling and selection, be clear about what is happening e.g. instead of MANUAL_POLLING it could be MANUAL_INPUT_GAME_OR_DRINK and instead of MANUAL_SELECTION it could be MANUAL_INPUT_DRINK_CHOICE etc.

2019-03-07 22:30 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +    case START:
Make sure to rename these if you rename your enums

2019-03-07 22:30 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +  enum stateMachine nextState;
Remove code in function.

2019-03-07 22:31 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +{
Remove code in function.

2019-03-07 22:31 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +  enum stateMachine nextState;
Remove code in function.

2019-03-07 22:31 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +{
Remove code in function.

2019-03-07 22:31 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +{
Remove code in function.

2019-03-07 22:31 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +{
Remove code in function.

2019-03-07 22:34 UTC, rshii requested changes
Save all the code that I've mentioned to remove on a personal file, and make the following changes. Also, make sure you can compile (verify) your code in the arduino IDE.

2019-03-14 22:07 UTC, rshii requested changes
Needs a lot of work

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +#if (ARDUINO >= 100)
Get rid of this

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +  int Bin1;
Refer to Tauheed's pinLayout module to populate these pins

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +#include "Arduino.h"
Header files at the top.

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +  Bin1 = 22;
Refer to previous comment about the pinLayout.

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +  int Bin1;
Also variables are to be camelCase.

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +
Whitespace

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +// ELEC 3907: Header file to get pumps going in skeleton
Why are there two files?

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +#define game_Control_h
Make sure you know what these defines are doing

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +  while(polling == true)
Polling is fine, I can add the timeout in a later commit

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +  while(polling == true)
There is a potential bug here as well depending on how reliable the LDR sensors are, in this case, a single pulse of HIGH reading will return the result, but that pulse could have been a bad reading, I maybe need to include a timer in a later commit.

2019-03-14 22:07 UTC, rshii commented on game_Control .h and .cpp
> +// ELEC 3907:
Separate the header content and cpp content into two clearly defined files

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +// ELEC 3907: Header file to get pumps going in skeleton
Oh I see this is the motor control module, make sure to separate cpp and header content into two files and actually name them.

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +#if (ARDUINO >= 100)
Get rid of this.

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  pumpControl(int MotorOutA, int MotorInA, int MotorOutB, int MotorInB);
Again refer to Tauheed about how to effectively use his pinLayout module

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  int motoroutA;
Strictly use camelCase for variables.

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  void Dispense_Drink_A();
To be honest, having all these custom methods will not work as you will see when we implement custom recipes. That custom recipe dispense drink method will take two arguments and dispense a drink accordingly, and it will be **flexible** because of that. Every one of your dispense methods here could be represented by that single method. Try to implement it, it's not too hard and is a way better design.

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  int flow_out;
What do these variables mean? Consider renaming them

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +#include "Arduino.h"
Includes at the top

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  flow_out = 10000;
Replace constants with defines, otherwise these waste memory for no reason

2019-03-14 22:07 UTC, rshii commented on pump_Control .h and .cpp
> +  motoroutA = MotorOutA;
Again refer to Tauheed's pinLayout

2019-03-14 22:07 UTC, rshii commented on Drinking-Machine-Arduino-Code.ino
> +const int plinkoBin1 = 22;
Refer to Tauheed's pinLayout

2019-11-17 18:35 UTC, Tauheed-Elahee commented
Close pull request do to too many conflicts with the main branch.

2019-11-17 18:35 UTC, closed without merging